### ISSUE TITLE
Fix addProgressListener usage

### ISSUE THREAD

**Issue by daveschaefer** [danwent/Perspectives#103]
If you open the Browser Console in Firefox (Ctrl + Shift + J) when the browser opens, you see a warning about Perspectives:

>gBrowser.addProgressListener was called with a second argument, which is not supported. See bug 608628.
>Call stack: addProgressListener@chrome://browser/content/tabbrowser.xml:2286
@chrome://perspectives/content/notaries.js:926
>evtLoad@chrome://perspectives/content/initialize.xul:14

[Bug 608628](https://bugzilla.mozilla.org/show_bug.cgi?id=608628)

suggests:
>If you're passing NOTIFY_ALL as the second parameter, just remove it.
>If you're passing something else, it depends on what your code actually wants. If it wants only certain progress notifications, it's broken. If it actually wants all progress notifications, the second parameter was used wrongly and can be removed without a replacement.

We're passing NOTIFY_STATE_DOCUMENT. If we're not interested in all notifications we may need to fix this.

**Comment by daveschaefer** [comment]
I have received the AMO review results for Perspectives version 4.6. This issue was identified as something we need to fix before they will bless v4.6 will full approval. It looks like until we fix that v4.6 may not be displayed on the AMO site - https://addons.mozilla.org/en-US/developers/docs/policies/reviews#selection . So fixing this is now a much higher priority.

**Comment by netsafe** [comment]
Fixed - see my commit

**Comment by daveschaefer** [comment]
This has now finally been through the review process at AMO and can be downloaded :) - https://addons.mozilla.org/en-US/firefox/addon/perspectives/versions/4.6.2
