### ISSUE TITLE
AMO review - clean up nsIDNSService.resolve()

### ISSUE THREAD

**Issue by daveschaefer** [danwent/Perspectives#160]
"`nsIDNSService.resolve()` should not be used. The `nsIDNSService.resolve` method performs a synchronous DNS lookup, which will freeze the UI. This can result in severe performance issues. `nsIDNSService.asyncResolve()` should be used instead."

I have received the AMO review results for Perspectives version 4.6. This issue was identified as something we need to fix before they will bless v4.6 will full approval. It looks like until we fix that v4.6 may not be displayed on the AMO site - https://addons.mozilla.org/en-US/developers/docs/policies/reviews#selection . So fixing this is now a much higher priority.

Note that this call is from the disabled 'report attack' functionality (see #49). For now we should be able to clean up the call easily because that functionality is now removed.

**Comment by netsafe** [comment]
IMHO attack report functionality must be reviewed and re-implemented in a new way, but not removed completely : this is a valueable feature, removing it is like a shooting your balls out

**Comment by daveschaefer** [comment]
@netsafe It would certainly be possible to keep some kind of 'report attack' functionality, but that can likely be done separately from this issue here.

Most of the 'report attack' notes are stored in #49.

**Comment by netsafe** [comment]
The fix is upcoming, based on the https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIDNSService manual. Give me some hours and it will fire-up!

**Comment by netsafe** [comment]
Done!

**Comment by daveschaefer** [comment]
This has now finally been through the review process at AMO and can be downloaded :) - https://addons.mozilla.org/en-US/firefox/addon/perspectives/versions/4.6.2
