### ISSUE TITLE
Perspectives icon moved to new menu item

### ISSUE THREAD

**Issue by daveschaefer** [danwent/Perspectives#161]
"Menu item has been moved. Your add-on has an overlay that uses the insertbefore or insertafter attribute pointing to menuitems that have been moved to a different menu item. Your overlay items may appear in unexpected locations because of this. See https://bugzilla.mozilla.org/show_bug.cgi?id=653221 for more information."

I have received the AMO review results for Perspectives version 4.6. This issue was identified as something we need to fix before they will bless v4.6 will full approval. It looks like until we fix that v4.6 may not be displayed on the AMO site - https://addons.mozilla.org/en-US/developers/docs/policies/reviews#selection . So fixing this is now a much higher priority.

This could match with a comment from the mailing list about the Perspectives icon not showing up.

**Comment by netsafe** [comment]
Fixed - see my pull request, tested and works OK

**Comment by daveschaefer** [comment]
This has now finally been through the review process at AMO and can be downloaded :) - https://addons.mozilla.org/en-US/firefox/addon/perspectives/versions/4.6.2
