### ISSUE TITLE
Initialization script too long

### ISSUE THREAD

**Issue by daveschaefer** [danwent/Perspectives#162]
From the AMO review results: "Long inline script. Please store complex scripts in .js files rather than inline script nodes. chrome/content/initialize.xul"

I have received the AMO review results for Perspectives version 4.6. This issue was identified as something we need to fix before they will bless v4.6 will full approval. It looks like until we fix that v4.6 may not be displayed on the AMO site - https://addons.mozilla.org/en-US/developers/docs/policies/reviews#selection . So fixing this is now a much higher priority.

I will contact the review to ask how long is "too long".

**Comment by netsafe** [comment]
Fixed and refactored - see my pull request, tested and works OK

**Comment by daveschaefer** [comment]
This has now finally been through the review process at AMO and can be downloaded :) - https://addons.mozilla.org/en-US/firefox/addon/perspectives/versions/4.6.2
