### ISSUE TITLE
Move preference variables to "extensions."

### ISSUE THREAD

**Issue by daveschaefer** [danwent/Perspectives#59]
Right now the preference variables are stored under "perspectives.*". We should move them to "extensions.perspectives.*", as detailed here: https://developer.mozilla.org/en/Extensions/Extension_etiquette

This will require an upgrade function to migrate prefs for anyone updating Perspectives.

**Comment by daveschaefer** [comment]
I have received the AMO review results for Perspectives version 4.6. This issue was identified as something we need to fix before they will bless v4.6 will full approval. It looks like until we fix that v4.6 may not be displayed on the AMO site - https://addons.mozilla.org/en-US/developers/docs/policies/reviews#selection . So fixing this is now a much higher priority.

"Extensions should not alter preferences outside of the 'extensions.' preference branch. Please make sure that all of your extension's preferences are prefixed with 'extensions.add-on-name.', where 'add-on-name' is a distinct string unique to and indicative of your add-on."

**Comment by netsafe** [comment]
Fixed

**Comment by daveschaefer** [comment]
Hey, I'm back. Okay, working to test this and send to AMO now.

It looks really good. There is one bug I'm checking to see if it's an actual issue with upgrading (unrelated to your code) or a bug that happens all of the time. It looks like the latter. If so I will push the patch and get this rolling.

Thanks again!

**Comment by daveschaefer** [comment]
Okay, I've solved the bug :) There was an issue where sometimes the `root_prefs` object would be null and cause an error during the upgrade. It is now fixed.

Finishing testing and I hope to release this within 1 week.

**Comment by daveschaefer** [comment]
Okay! PR #173 takes care of fixing the preference location! I cherrypicked and merged netsafe's other two commits and published it.

The changes have been uploaded to AMO and we are now waiting for review. Once they give us approval we should be back to normal publishing updates!
